[project]
dependencies = [
  "aiosmtplib>=5.1.2",
  "aiosqlite>=0.22.1",
  "alembic>=1.18.5",
  "boto3>=1.43.56",
  "certifi>=2025.1.31",
  "fastapi[standard]>=0.139.0",
  "greenlet>=3.5.3",
  "pillow>=12.3.0",
  "psycopg[binary]>=3.3.4",
  "pwdlib[argon2]>=0.3.0",
  "pydantic-settings>=2.14.2",
  "pyjwt>=2.13.0",
  "sqlalchemy>=2.0.51",
]
description = "Add your description here"
name = "hero-blog"
readme = "README.md"
requires-python = ">=3.14"
version = "0.1.0"

[dependency-groups]
dev = [
  "moto[s3]>=5.2.2",
  "pytest>=9.1.1",
]
